spring.application.name=blog-platform-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/blogplatform
spring.datasource.username=blogplatformadmin
spring.datasource.password=blogplatformlogin@1
spring.jpa.hibernate.ddl-auto=update
spring.datasource.show-sql=true
